[project]
name = "docsconvert"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "html2text>=2025.4.15",
    "lxml>=6.0.2",
    "mammoth>=1.11.0",
    "pdfplumber>=0.11.9",
    "pymupdf==1.26.6",
    "pymupdf4llm[layout,ocr]>=0.2.9",
    "opencv-python>=4.12.0.88",
    "pymupdf-layout>=1.26.6",
    "pypandoc-binary>=1.16.2",
    "python-docx>=1.2.0",
    "docling>=2.68.0",
    "markitdown>=0.1.4",
    "opencv-python-headless>=4.12.0.88",
    "marker-pdf[full]>=1.9.2",
    "streamlit>=1.53.0",
    "streamlit-ace>=0.1.1",
]
